// <auto-generated />
namespace MVC5Rev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CustomVal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomVal));
        
        string IMigrationMetadata.Id
        {
            get { return "202103231841116_CustomVal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
